/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportRouteImport } from './routes/sport'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MiljoRouteImport } from './routes/miljo'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as IndexRouteImport } from './routes/index'

const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MiljoRoute = MiljoRouteImport.update({
  id: '/miljo',
  path: '/miljo',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/miljo': typeof MiljoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/miljo': typeof MiljoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/miljo': typeof MiljoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integritetspolicy'
    | '/kontakt'
    | '/miljo'
    | '/sitemap.xml'
    | '/sport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integritetspolicy'
    | '/kontakt'
    | '/miljo'
    | '/sitemap.xml'
    | '/sport'
  id:
    | '__root__'
    | '/'
    | '/integritetspolicy'
    | '/kontakt'
    | '/miljo'
    | '/sitemap.xml'
    | '/sport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  MiljoRoute: typeof MiljoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportRoute: typeof SportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miljo': {
      id: '/miljo'
      path: '/miljo'
      fullPath: '/miljo'
      preLoaderRoute: typeof MiljoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  MiljoRoute: MiljoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportRoute: SportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
